version: "3.8"
services:
    rhasspy:
        image: "rhasspy/rhasspy"
        container_name: rhasspy
        restart: unless-stopped
        volumes:
            - "./rhasspy/profiles:/profiles"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - "12101:12101"
        devices:
            - "/dev/snd:/dev/snd"
        command: --user-profiles /profiles --profile fr

    node-red:
        build:
            context: ./node-red-build
        container_name: nodered
        environment:
            - TZ=Europe/Paris
        ports:
            - "1880:1880"
        volumes:
            - "./node-red/data:/data:rw"
            - "./node-red/tools:/tools:ro"
        devices:
            - "/dev/snd:/dev/snd"
            - "/dev/ttyAMA0:/dev/ttyAMA0"
        privileged: true
